name: DevSkim

on:
  push:
    branches: [master]
  schedule:
    - cron: 30 9 * * 1

permissions:
  contents: read

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Run DevSkim scan
        uses: microsoft/DevSkim-Action@a6b6966a33b497cd3ae2ebc406edf8f4cc2feec6
        with:
          directory-to-scan: ./src/

      - name: Upload DevSkim scan results
        uses: github/codeql-action/upload-sarif@5f8171a638ada777af81d42b55959a643bb29017
        with:
          sarif_file: devskim-results.sarif
