name: OSSF Scorecard

on:
  push:
    branches: [master]
  schedule:
    - cron: 30 9 * * 1

permissions: read-all

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@f49aabe0b5af0936a0987cfb85d86b75731b0186
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@6bb031afdd8eb862ea3fc1848194185e076637e5
        with:
          sarif_file: results.sarif
